max_width                   = 80
tab_spaces                  = 2
format_macro_matchers       = true
format_code_in_doc_comments = true
wrap_comments               = true
imports_granularity         = "Module"
edition                     = "2024"
