max_width                    = 80
tab_spaces                   = 2
format_macro_matchers        = true
format_code_in_doc_comments  = true
format_macro_bodies          = true
use_field_init_shorthand     = true
struct_lit_single_line       = true
struct_field_align_threshold = 20
wrap_comments                = true
imports_granularity          = "Item"
edition                      = "2024"
